In [72]:
import tensorflow.compat.v1 as tf
from tensorflow import feature_column
from tensorflow.keras import layers
tf.disable_v2_behavior()
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

from tensorflow import keras
from tensorflow.keras.models import Sequential # 케라스의 Sequential()을 임포트
from tensorflow.keras.layers import Dense # 케라스의 Dense()를 임포트
from tensorflow.keras import optimizers # 케라스의 옵티마이저를 임포트
%matplotlib inline

In [73]:
seed = 0
# a = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))
# b = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))

# tensorflow, numpy 랜덤 값을 설정합니다.
tf.set_random_seed(seed)
np.random.seed(seed)

In [74]:
#doginfo.csv파일 데이터를 pandas를 이용해 읽어옵니다.
dog_data=pd.read_csv("doginfo_mmy.csv")
dog_train=pd.read_csv("testDog.csv")
kindCd=pd.read_csv("kindCd.csv")

dog_data = dog_data.dropna(axis=0)
dog_train = dog_train.dropna(axis=0)
kindCd_data = kindCd.dropna(axis=0)

dog_data
# print(dog_train)
# print(kindCd)

kindNum neuterYn sexCd  weight  noticeDays  age2  processState
0       128.0        N     F    7.46          10    12             0
1       114.0        N     M    7.00          14     1             1
2       114.0        U     M    4.50          11     2             0
3        67.0        N     M   10.00           8     1             0
4       114.0        N     M    6.00           8     4             0
...       ...      ...   ...     ...         ...   ...           ...
1994    114.0        N     M    0.98          10     0             1
1995    114.0        N     F    1.20          10     0             1
1996    106.0        N     M   50.00          10     3             1
1997    114.0        U     F    9.00          10     3             0
1998    114.0        N     F   12.50          10     3             0

[1995 rows x 7 columns]

In [75]:
# dog_data['sexF']=dog_data['sexCd'].apply(lambda x:1 if x=='F' else 0)
# dog_data['sexM']=dog_data['sexCd'].apply(lambda x:1 if x=='M' else 0)
# dog_data['sexQ']=dog_data['sexCd'].apply(lambda x:1 if x=='Q' else 0)

# dog_data['neuterY']=dog_data['neuterYn'].apply(lambda x:1 if x=='Y' else 0)
# dog_data['neuterN']=dog_data['neuterYn'].apply(lambda x:1 if x=='N' else 0)
# dog_data['neuterU']=dog_data['neuterYn'].apply(lambda x:1 if x=='U' else 0)
# dog_data

dog_data['sexCd']=dog_data['sexCd'].map({'F':1, 'M':0, 'Q':2})
dog_data['neuterYn']=dog_data['neuterYn'].map({'Y':1, 'N':0, 'U':2})

dog_train['sexCd']=dog_train['sexCd'].map({'F':1, 'M':0, 'Q':2})
dog_train['neuterYn']=dog_train['neuterYn'].map({'Y':1, 'N':0, 'U':2})

In [76]:
dog_data=np.array(dog_data)
dog_train=np.array(dog_train)

# a = dog_data[:, :3]
# b = dog_data[:, 4:]

# print(a[0,:])
# print(b)

#numpy 배열에서 데이터 변화요인(kindCd, neuterYn, sexCd, weight, noticeDays, age2)으로 사용할 데이터를 뽑아냅니다.
xData = dog_data[:, :6]

# a=dog_train[:, :3]
# b=dog_train[:, 4:]
testX=dog_train[:, :6]

print(xData)
# type(xData)
# xData.shape

[[128.     0.     1.     7.46  10.    12.  ]
 [114.     0.     0.     7.    14.     1.  ]
 [114.     2.     0.     4.5   11.     2.  ]
 ...
 [106.     0.     0.    50.    10.     3.  ]
 [114.     2.     1.     9.    10.     3.  ]
 [114.     0.     1.    12.5   10.     3.  ]]


In [77]:
#numpy배열에서 결과(입양여부)로 사용할 데이터를 뽑아냅니다.
yData=dog_data[:,[6]]
testY=dog_train[:,[6]]
# yData = yData.astype('int32')
print(yData)
type(yData)
yData.dtype

[[0.]
 [1.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]]


dtype('float64')

In [78]:
def model_performance(y_test, y_pred):    
    print('confusion matrix')
    print(metrics.confusion_matrix(y_test, y_pred))
    print('accuracy : {}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('precision : {}'.format(metrics.precision_score(y_test, y_pred)))
    print('recall : {}'.format(metrics.recall_score(y_test, y_pred)))
    print('F1 : {}'.format(metrics.f1_score(y_test, y_pred)))

In [79]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
# model = RandomForestClassifier()
# model.fit(X_all_train, y_train)
# y_pred = model.predict(X_all_test)
# model_performance(y_test, y_pred)


model = RandomForestClassifier(n_estimators=100, max_depth=12, min_samples_leaf=3, min_samples_split=16)
rf_model=model.fit(xData, yData)
y_pred = rf_model.predict(testX)
model_performance(testY, y_pred)

C:\Users\auddu\anaconda3\envs\auddus\lib\site-packages\ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


confusion matrix
[[185 123]
 [ 96 206]]
accuracy : 0.6409836065573771
precision : 0.6261398176291794
recall : 0.6821192052980133
F1 : 0.652931854199683


In [71]:
# testX.shape
rf_model.predict_proba(testX[:6])

array([[0.09601083, 0.90398917],
       [0.5835028 , 0.4164972 ],
       [0.76038066, 0.23961934],
       [0.09540756, 0.90459244],
       [0.84608651, 0.15391349],
       [0.84608651, 0.15391349]])

In [62]:
# from sklearn.external.joblib as extjoblib
import joblib
joblib.dump(rf_model, 'randomforest.pkl')

['randomforest.pkl']