In [120]:
import tensorflow.compat.v1 as tf
from tensorflow import feature_column
from tensorflow.keras import layers
tf.disable_v2_behavior()
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

%matplotlib inline

In [121]:
#doginfo.csv파일 데이터를 pandas를 이용해 읽어옵니다.
dog_data=pd.read_csv("doginfo.csv")
print(dog_data.head())


  kindCd  kindNum neuterYn sexCd  weight  noticeDays  age2  processState  \
0     푸들    128.0        N     F    7.46          10    12             0   
1    믹스견    114.0        N     M    7.00          14     1             1   
2    믹스견    114.0        U     M    4.50          11     2             0   
3    진도견     67.0        N     M   10.00           8     1             0   
4    믹스견    114.0        N     M    6.00           8     4             0   

   Unnamed: 8   kindCd.1  kindNum.1  
0         NaN    골든 리트리버       54.0  
1         NaN    그레이 하운드       56.0  
2         NaN     그레이트 덴       55.0  
3         NaN  그레이트 피레니즈      118.0  
4         NaN         기타      115.0  


In [122]:
# example_batch= next(iter(train_ds))[0]
# def demo(feature_column):
#     feature_layer = layers.DenseFeatures(feature_column)
#     print(feature_layer(example_batch).numpy())

In [123]:
# kindCd_embedding=feature_column.embedding_column(kindCd, dimension=114)
# demo(kindCd_embedding)

#읽어온 데이터를 파이썬에서 처리하기 적합하게 numpy 배열 형태로 변환합니다.

dog_data.loc[dog_data["neuterYn"] == "N", "neuterYn"] = 0
dog_data.loc[dog_data["neuterYn"] == "U", "neuterYn"] = 1
dog_data.loc[dog_data["neuterYn"] == "Y", "neuterYn"] = 2

dog_data.loc[dog_data["sexCd"] == "M", "sexCd"] = 0
dog_data.loc[dog_data["sexCd"] == "F", "sexCd"] = 1
dog_data.loc[dog_data["sexCd"] == "Q", "sexCd"] = 2

# del dog_data['kindCd']
# del dog_data['kindCd.1']

dog_data.drop(['kindCd', 'Unnamed: 8', 'kindCd.1', 'kindNum.1'], axis='columns', inplace=True)


data=np.array(dog_data, dtype=np.float32)


print(data)
print(type(data))

[[128.   0.   1. ...  10.  12.   0.]
 [114.   0.   0. ...  14.   1.   1.]
 [114.   1.   0. ...  11.   2.   0.]
 ...
 [114.   0.   0. ...  10.   0.   1.]
 [128.   1.   1. ...  12.   3.   0.]
 [114.   0.   0. ...  10.   0.   0.]]
<class 'numpy.ndarray'>


In [124]:
#numpy 배열에서 데이터 변화요인(kindCd, neuterYn, sexCd, weight, noticeDays, age2)으로 사용할 데이터를 뽑아냅니다.
xData=data[:, :6]
print(xData)

[[128.     0.     1.     7.46  10.    12.  ]
 [114.     0.     0.     7.    14.     1.  ]
 [114.     1.     0.     4.5   11.     2.  ]
 ...
 [114.     0.     0.     1.    10.     0.  ]
 [128.     1.     1.     6.    12.     3.  ]
 [114.     0.     0.     3.5   10.     0.  ]]


In [125]:
#numpy배열에서 결과(입양여부)로 사용할 데이터를 뽑아냅니다.
yData=data[:,[6]]
print(yData)

[[0.]
 [1.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]]


In [129]:
#뽑아낸 데이터를 tensorflow로 처리하기 위해 placeholder를 만듭니다.
X=tf.placeholder(dtype=tf.float32, shape=[None, 6])
Y=tf.placeholder(dtype=tf.float32, shape=[None, 1])
#다변인 선형 회귀 모델의 기울기와 y절편을 임의의 값으로 초기화합니다.
a=tf.Variable(tf.random_uniform([6, 1], dtype=tf.float32))#6행 1열 난수를 발생시킵니다.
b=tf.Variable(tf.random_uniform([1], dtype=tf.float32)) #1행 1열 난수를 발생시킵니다.
# print(X)
# print(a)

In [135]:
# #행렬의 곱셈 연산을 이용해 다변인 성형 회귀 모델의 가설 식을 세웁니다. ->예측값
# y=tf.matmul(X, a)+b
# #y=tf.clip_by_value(y, 1e-5, 1-(1e-5))

# #오차 함수를 만듭니다.
# loss= tf.reduce_mean(tf.square(y-Y))
# #loss= tf.clip_by_value(loss, 1e-5, 1-(1e-5))

# #경사하강법 알고리즘을 사용해서 오차 함수 결과를 최소로 하는 식을 만듭니다. 
# gradient_descent=tf.train.GradientDescentOptimizer(0.1).minimize(loss)


# 시그모이드 방정식을 만듭니다.
y = tf.sigmoid(tf.matmul(X, a) + b)
# 오차 함수
loss = -tf.reduce_mean(Y * tf.log(y) + (1 - Y) * tf.log(1 - y))
# 경사 하강 알고리즘
gradient_descent = tf.train.GradientDescentOptimizer(0.01).minimize(loss)

In [136]:
# sigmoid() 함수의 실행 결과(y) 값이 0.5 이상이면 1을 0.5 미만이면 0을 리턴시킵니다.
# tf.cast(캐스팅할 데이터, dtype=캐스팅 될 데이터 타입) : tensorflow에서 형변환을 실행하는 함수
# predicted = tf.cast(tf.constant([1.9, 2.1]), dtype=tf.int32)  # [1, 2] -> 실수(부동소수점 데이터)를 정수형 데이터로 변경합니다.
# predicted = tf.cast(0.4 >= 0.5, dtype = tf.float64)  # 조건 비교 결과가 False이므로 0으로 캐스팅
# predicted = tf.cast(0.5 >= 0.5, dtype = tf.float64)  # 조건 비교 결과가 True이므로 1으로 캐스팅

predicted = tf.cast(y >= 0.5, dtype = tf.float32)

# 예상값이 실제값과 일치하는 정도(정확도)를 계산합니다.
# tf.equal(): tensorflow에서 인수로 지정된 값이 같으면 True, 다르면 False 결과를 tf.float64로 캐스팅 시키고 시행된 전체 평균을 계산합니다.
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float64))  # 정확도 (0 또는 1)

In [137]:
# #학습을 시킨 후 학습된 모델을 저장합니다.
# with tf.Session() as sess:
#     sess.run(tf.global_variables_initializer())
#     for i in range(10001):
#         loss_, y_, _ = sess.run([loss, y, gradient_descent], feed_dict={X:xData, Y:yData})
#         if i % 500 ==0:
#             print("count:%6d, loss=%12.3f. print=%6.1f" %(i, loss_, y_[0]))


with tf.Session() as sess:  # 세션 구간을 만듦
    sess.run(tf.global_variables_initializer())
    for i in range(3001):
        # count : 학습 횟수, a1 : 기울기(공부 시간), a2 : 기울기(과외 시간), b : y절편, loss : 오차 함수
        a_, b_, loss_, _ = sess.run([a, b, loss, gradient_descent], feed_dict = {X:xData, Y:yData})
        if i % 300 == 0:
            print('count : {}, a1 = {}, a2 = {}, a3 = {}, a4 = {}, a5 = {}, a6 = {}, b = {}, loss = {}'.format(i, a_[0], a_[1], a_[2], a_[3], a_[4], a_[5], b_, loss_)) # 학습시킨 데이터 출력
            
# 학습 완료 -----------------------------------------------------------------------------------------------------
# 테스트 데이터

#     new_x = np.array([6, 5]).reshape(1, 6)  # reshape() 함수를 이용해서 1행 2열인 2차원 numpy 배열을 만듭니다.
    
#     # sigmoid() 함수 연산 결과에 테스트 데이터를 대입시켜 연산합니다.
#     result, new_y = sess.run([predicted, y], feed_dict = {X:new_x})
#     print('공부 시간 : %d, 과외 시간 : %d' % (new_x[:, 0], new_x[:, 1]))
#     print('합격 여부(sigmoid() 함수 실행 결과를 0.5 이상은 1, 미만은 0으로 반환) : %d, 합격 확률(sigmoid() 함수 실행 결과) : %f)' % (result, new_y))
    
#     for i in range(11):
# #         new_x = np.array([0, i]).reshape(1, 6)  # 과외 시간만 계속 늘림
#         result, new_y = sess.run([predicted, y], feed_dict={X:new_x})
# #         print('품종 : %d, 과외 시간 : %2d, ' % (new_x[:, 0], new_x[:, 1]), end=',')
#         print('입양 여부 : %s, 입양 확률 : %8.4f%%' % ('합격' if result == 1 else '불합격', new_y*100))


# 학습이 완료되면 학습된 모델을 디스크에 저장합니다.
# tf.train.Saver(): 학습된 모델을 디스트로 저장 또는 불로오는 객체를 생성하는 함수
    saver= tf.train.Saver()
    saver_path=saver.save(sess, './dogsave.ckpt')

count : 0, a1 = [nan], a2 = [nan], a3 = [nan], a4 = [nan], a5 = [nan], a6 = [nan], b = [nan], loss = nan
count : 300, a1 = [nan], a2 = [nan], a3 = [nan], a4 = [nan], a5 = [nan], a6 = [nan], b = [nan], loss = nan
count : 600, a1 = [nan], a2 = [nan], a3 = [nan], a4 = [nan], a5 = [nan], a6 = [nan], b = [nan], loss = nan
count : 900, a1 = [nan], a2 = [nan], a3 = [nan], a4 = [nan], a5 = [nan], a6 = [nan], b = [nan], loss = nan
count : 1200, a1 = [nan], a2 = [nan], a3 = [nan], a4 = [nan], a5 = [nan], a6 = [nan], b = [nan], loss = nan
count : 1500, a1 = [nan], a2 = [nan], a3 = [nan], a4 = [nan], a5 = [nan], a6 = [nan], b = [nan], loss = nan
count : 1800, a1 = [nan], a2 = [nan], a3 = [nan], a4 = [nan], a5 = [nan], a6 = [nan], b = [nan], loss = nan
count : 2100, a1 = [nan], a2 = [nan], a3 = [nan], a4 = [nan], a5 = [nan], a6 = [nan], b = [nan], loss = nan
count : 2400, a1 = [nan], a2 = [nan], a3 = [nan], a4 = [nan], a5 = [nan], a6 = [nan], b = [nan], loss = nan
count : 2700, a1 = [nan], a2 = [na