In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.set_random_seed(777)
import numpy as np
import pandas as pd
import math

Instructions for updating:
non-resource variables are not supported in the long term


In [28]:
seed = 0
# a = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))
# b = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))

# tensorflow, numpy 랜덤 값을 설정합니다.
tf.set_random_seed(seed)
np.random.seed(seed)

In [29]:
#doginfo.csv파일 데이터를 pandas를 이용해 읽어옵니다.
dog_data=pd.read_csv("doginfo.csv")
print(dog_data.head())

  kindCd  kindNum neuterYn sexCd  weight  noticeDays  age2  processState  \
0     푸들    128.0        N     F    7.46          10    12             0   
1    믹스견    114.0        N     M    7.00          14     1             1   
2    믹스견    114.0        U     M    4.50          11     2             0   
3    진도견     67.0        N     M   10.00           8     1             0   
4    믹스견    114.0        N     M    6.00           8     4             0   

   Unnamed: 8   kindCd.1  kindNum.1  
0         NaN    골든 리트리버       54.0  
1         NaN    그레이 하운드       56.0  
2         NaN     그레이트 덴       55.0  
3         NaN  그레이트 피레니즈      118.0  
4         NaN         기타      115.0  


In [30]:
dog_data.loc[dog_data["neuterYn"] == "N", "neuterYn"] = 0
dog_data.loc[dog_data["neuterYn"] == "U", "neuterYn"] = 1
dog_data.loc[dog_data["neuterYn"] == "Y", "neuterYn"] = 2

dog_data.loc[dog_data["sexCd"] == "M", "sexCd"] = 0
dog_data.loc[dog_data["sexCd"] == "F", "sexCd"] = 1
dog_data.loc[dog_data["sexCd"] == "Q", "sexCd"] = 2

dog_data.drop(['kindCd', 'Unnamed: 8', 'kindCd.1', 'kindNum.1'], axis='columns', inplace=True)

data=np.array(dog_data, dtype=np.float64)


print(data)
print(type(data))

[[128.   0.   1. ...  10.  12.   0.]
 [114.   0.   0. ...  14.   1.   1.]
 [114.   1.   0. ...  11.   2.   0.]
 ...
 [114.   0.   0. ...  10.   0.   1.]
 [128.   1.   1. ...  12.   3.   0.]
 [114.   0.   0. ...  10.   0.   0.]]
<class 'numpy.ndarray'>


In [31]:
xData=data[:, :6]
print(xData)

[[128.     0.     1.     7.46  10.    12.  ]
 [114.     0.     0.     7.    14.     1.  ]
 [114.     1.     0.     4.5   11.     2.  ]
 ...
 [114.     0.     0.     1.    10.     0.  ]
 [128.     1.     1.     6.    12.     3.  ]
 [114.     0.     0.     3.5   10.     0.  ]]


In [32]:
yData=data[:,[6]]
print(yData)

[[0.]
 [1.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]]


In [41]:
X=tf.placeholder("float", shape=[None, 6])
Y=tf.placeholder("float", shape=[None, 1])

W=tf.Variable(tf.random_normal([6,1]))#6행 1열 난수를 발생시킵니다.
b=tf.Variable(tf.random_normal([1])) #1행 1열 난수를 발생시킵니다.
print(X, Y, W, b)

Tensor("Placeholder_24:0", shape=(?, 6), dtype=float32) Tensor("Placeholder_25:0", shape=(?, 1), dtype=float32) <tf.Variable 'Variable_24:0' shape=(6, 1) dtype=float32_ref> <tf.Variable 'Variable_25:0' shape=(1,) dtype=float32_ref>


In [24]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

In [25]:
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [26]:
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: xData, Y: yData})
        print(step, cost_val, W_val)

0 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
2 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
3 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
4 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
5 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
6 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
7 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
8 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
9 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
10 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
11 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
12 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
13 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
14 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
15 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
16 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
17 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
18 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
19 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
20 nan [[n